
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwjzvylxdrnzxqdstdkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3anp2eWx4ZHJuenhxZHN0ZGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NzU1NzksImV4cCI6MjA2MjA1MTU3OX0.YOBywhqrq_bF25u7rG3HDW8HI8GWubcbKSXyhtVvF3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
